### ISSUE TITLE
Cosmic Cuttlefish (18.10) is no longer supported which is causing CI build failures

### ISSUE THREAD

**Issue by leematos** [onivim/libvim#179]
https://wiki.ubuntu.com/CosmicCuttlefish/ReleaseNotes

Do you have a preference as to what image to target instead?

**Comment by bryphe** [comment]
Ah, sorry I missed this @leematos !

I switched the Ubuntu 18.x strategy to just use the Azure CI image in this PR: https://github.com/onivim/libvim/pull/181

Looks like builds are green now.
