### ISSUE TITLE
step backwards from neovim?

### ISSUE THREAD

**Issue by trusktr** [onivim/libvim#256]
Seems like one of neovim's original goals was to go from sync key handling to async key handling to improve performance. This takes a step back, back to sync handling.

Will this have the issues that Neovim solved (namely vim plugins that slow the user experience down, f.e. long wait times to process key press actions, especially movement actions), once we start adding various Vim plugins?

**Comment by bryphe** [comment]
Our Onivim v2 design doc talks about why we moved from asynchronous to synchronous key handling: https://onivim.github.io/docs/other/motivation#reduced-rpc-calls
